export const ACTION_TYPES = {
  // CRUD Actions
  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  DELETE_CONTACT_SUCCESS: "DELETE_CONTACT_SUCCESS",
  DELETE_SELECTED_SUCCESS: "DELETE_SELECTED_SUCCESS",

  // UI / State Controls
  UPDATE_CURRENT_CONTACT: "UPDATE_CURRENT_CONTACT",
  SET_ERRORS: "SET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
  SET_SEARCH: "SET_SEARCH",
  SET_SELECTED_IDS: "SET_SELECTED_IDS",
  SET_EDITING_ID: "SET_EDITING_ID",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  RESET_STATE: "RESET_STATE",
};

